# Generated by Django 2.1.7 on 2019-08-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestito',
            name='DataPrenotazione',
            field=models.DateTimeField(),
        ),
    ]
