# Generated by Django 2.1.7 on 2019-09-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_auto_20190826_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestito',
            name='Estensione',
            field=models.BooleanField(default=False),
        ),
    ]
