# Generated by Django 2.1.7 on 2019-09-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_prestito_estensione'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestito',
            name='DataRestituzione',
            field=models.CharField(default='', max_length=30),
        ),
    ]
