# Generated by Django 2.1.7 on 2019-09-07 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0006_notifica'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifica',
            name='Utente',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
