# Generated by Django 2.1.7 on 2019-09-07 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0007_notifica_utente'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notifica',
            new_name='Avvisi',
        ),
    ]
