# Generated by Django 2.1.7 on 2019-09-13 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0008_auto_20190907_0355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='Cognome_Autore',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='ISBN13',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='Nome_Autore',
        ),
    ]
