# Generated by Django 2.1.7 on 2019-09-17 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0009_auto_20190913_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='Numero_Copie',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recensione',
            name='Valutazione',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
