# Generated by Django 2.1.7 on 2019-09-17 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0010_auto_20190917_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='Numero_Copie',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='recensione',
            name='Valutazione',
            field=models.IntegerField(null=True),
        ),
    ]
