# Generated by Django 2.1.7 on 2019-09-17 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0011_auto_20190917_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recensione',
            name='Valutazione',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
