# Generated by Django 2.1.7 on 2019-09-17 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0013_auto_20190917_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='DataDiPubblicazione',
            field=models.DateField(default=0.0004970178926441351),
        ),
    ]
