# Generated by Django 2.1.7 on 2019-09-17 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0015_remove_libro_datadipubblicazione'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='DataDiPubblicazione',
            field=models.DateField(auto_now=True),
        ),
    ]
