# Generated by Django 2.1.7 on 2019-09-17 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0016_libro_datadipubblicazione'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recensione',
            name='Genere',
        ),
        migrations.RemoveField(
            model_name='recensione',
            name='Titolo_Libro',
        ),
    ]
